// Typed access to First Leaf's fictional data. Every JSON file in this folder
// has an interface and a loader here. The JSON is generated by
// scripts/generate-data.mjs (only glossary.json is hand-written): never edit it
// by hand.
//
// Screens don't read accounts, activity or attention directly. They go through
// useScenario(), which picks the account for the current demo scenario.

import metaJson from './meta.json'
import personaJson from './persona.json'
import fundsJson from './funds.json'
import accountJson from './account.json'
import accountAllClearJson from './account-all-clear.json'
import accountNewJson from './account-new.json'
import activityJson from './activity.json'
import attentionJson from './attention.json'
import scenariosJson from './scenarios.json'
import practiceJson from './practice.json'
import storyJson from './story-p302.json'
import glossaryJson from './glossary.json'

/** A date as YYYY-MM-DD. */
export type ISODate = string
export type Ticker = 'FL-BROAD' | 'FL-WORLD' | 'FL-BOND' | 'FL-GREEN' | 'FL-CALM'
export type AccountId = 'rosa-starter' | 'rosa-all-clear' | 'rosa-new'
export type ScenarioId = 'normal' | 'all-clear' | 'brand-new'
export type Severity = 'needs-you' | 'heads-up' | 'fyi'

// ── meta.json ────────────────────────────────────────────────────────────────
export interface Meta {
  product: string
  company: string
  asOf: ISODate
  lastClose: ISODate
  lastReview: ISODate
  cashWaitingThreshold: number
  wordOfTheDay: string
  currency: string
  fictional: boolean
  dataVersion: number
  disclaimer: string
}

// ── persona.json ─────────────────────────────────────────────────────────────
export interface Persona {
  id: string
  firstName: string
  age: number
  city: string
  job: string
  fictional: boolean
  story: string
  worries: string[]
  devices: { phone: string; laptop: string }
  moments: { P301: string; P302: string; P303: string }
}

// ── funds.json ───────────────────────────────────────────────────────────────
export interface PricePoint {
  date: ISODate
  close: number
}

export interface Fund {
  ticker: Ticker
  name: string
  fictional: boolean
  kind: 'stocks' | 'bonds' | 'reserve'
  region: string
  /** "Ups and downs" rating, 1 (calm) to 5 (bumpy). */
  upsAndDowns: number
  /** Yearly fee (expense ratio) in percent, e.g. 0.45 means 0.45%. */
  expenseRatioHistory: { effective: ISODate; value: number; announcedOn?: ISODate }[]
  dividend: { frequency: 'monthly' | 'quarterly'; annualRate: number } | null
  inside: string
  latestPrice: number
  history: { weekly: PricePoint[]; daily: PricePoint[] }
}

// ── account.json, account-all-clear.json, account-new.json ──────────────────
export interface Holding {
  ticker: Ticker
  shares: number
  price: number
  value: number
  costBasis: number
  gainLoss: number
  targetShare: number
}

export interface Goal {
  id: string
  name: string
  target: number
  targetDate: ISODate
  measures: 'moneyIn'
  plan: { first: number; monthly: number }
  plannedMoneyInToDate: number
  actualMoneyInToDate: number
  behindBy: number
  plannedMoneyInByTarget: number
  progress: number
}

export interface WeeklyChange {
  from: ISODate
  to: ISODate
  startBalance: number
  deposits: number
  withdrawals: number
  dividends: number
  marketChange: number
  endBalance: number
  totalChange: number
  byFund: { ticker: Ticker; change: number }[]
}

export interface Account {
  id: AccountId
  ownerId: string
  name: string
  fictional: boolean
  openedOn: ISODate
  asOf: ISODate
  lastClose: ISODate
  balance: number
  investedValue: number
  cash: number
  cashSince: ISODate | null
  moneyIn: number
  gainLoss: number
  gainLossPercent: number
  dividendsTotal: number
  recurringDeposit: { amount: number; dayOfMonth: number; startedOn: ISODate } | null
  autoInvest: { on: boolean; startedOn: ISODate | null; pausedOn: ISODate | null }
  targetMix: Partial<Record<Ticker, number>> | null
  holdings: Holding[]
  goal: Goal | null
  weeklyChange: WeeklyChange | null
  history: { date: ISODate; balance: number; moneyIn: number; cash: number }[]
}

// ── activity.json (keyed by account id) ──────────────────────────────────────
interface ActivityBase {
  id: string
  date: ISODate
  settledDate: ISODate
  amount: number
  status: 'completed' | 'returned'
}

export interface DepositActivity extends ActivityBase {
  type: 'deposit'
  kind: 'first' | 'recurring'
  returnedDate?: ISODate
  returnReason?: string
}

export interface BuyActivity extends ActivityBase {
  type: 'buy'
  ticker: Ticker
  shares: number
  price: number
  via: 'auto-invest'
}

export interface DividendActivity extends ActivityBase {
  type: 'dividend'
  ticker: Ticker
}

export type ActivityItem = DepositActivity | BuyActivity | DividendActivity

// ── attention.json (keyed by account id, most urgent first) ──────────────────
export interface FlagAction {
  kind: 'retry-deposit' | 'one-time-deposit' | 'auto-invest' | 'open-fund'
  label: string
  amount?: number
}

export interface AttentionFlag {
  id: string
  severity: Severity
  date: ISODate
  raisedOn: ISODate
  title: string
  body: string
  nextStep: string
  action: FlagAction | null
  amount: number
  terms: string[]
  route: 'activity' | 'overview' | 'fund'
  newSinceLastReview: boolean
  activityId?: string
  goalId?: string
  ticker?: Ticker
  feeFrom?: number
  feeTo?: number
}

// ── scenarios.json ───────────────────────────────────────────────────────────
export interface Scenario {
  id: ScenarioId
  label: string
  description: string
  accountId: AccountId
}

// ── practice.json ────────────────────────────────────────────────────────────
export interface PracticeRules {
  startingCash: number
  fictional: boolean
  minOrder: number
  maxDecimals: number
  fractionalShares: boolean
  tradeFee: number
  priceDate: ISODate
  funds: Ticker[]
  timeMachine: { from: ISODate; to: ISODate; series: 'weekly'; note: string }
}

// ── story-p302.json ──────────────────────────────────────────────────────────
export interface Saver {
  id: string
  name: string
  startAge: number
  monthly: number
  fictional: boolean
  yearly: { age: number; putIn: number; value: number }[]
  final: { putIn: number; value: number; earned: number }
}

export interface StoryClaim {
  id: string
  /** Which chapter of Your money story states it (1–4). */
  chapter: number
  text: string
}

/** Rosa's own facts for one account, recomputed by rules R1–R4. */
export interface RosaStory {
  accountId: AccountId
  pointOfView: string
  facts: {
    openedOn: ISODate
    firstDeposit: number
    moneyIn: number
    balance: number
    earned: number
    depositsShare: number
    lastClose: ISODate
    dip: {
      ticker: Ticker
      window: { from: ISODate; to: ISODate }
      highDate: ISODate
      high: number
      lowDate: ISODate
      low: number
      drop: number
    }
    atLow: { date: ISODate; balance: number; moneyIn: number; below: number }
    pause: { date: ISODate } | null
    after: {
      backAboveDate: ISODate
      backAboveBalance: number
      backAboveMoneyIn: number
      deposits: { date: ISODate; amount: number }[]
      depositsInvested: boolean
      upNow: number
    }
  }
  claims: StoryClaim[]
}

export interface Story {
  id: string
  title: string
  fictional: boolean
  pointOfView: string
  assumptions: {
    annualRate: number
    compounding: string
    contributionTiming: string
    endAge: number
    note: string
  }
  savers: Saver[]
  catchUp: {
    saverId: string
    mustMatch: string
    monthlyNeeded: number
    slider: { min: number; max: number; step: number }
  }
  startAgeSlider: { min: number; max: number; step: number; monthly: number }
  bumpy: {
    seed: number
    yearlyReturns: number[]
    overallGrowth: number
    nia: { age: number; value: number }[]
    theo: { age: number; value: number }[]
    note: string
  }
  yourTurn: { personaId: string; startAge: number; monthly: number; note: string }
  claims: { id: string; text: string }[]
  sources: { label: string; url: string }[]
  /** Per account; null for an account with no history yet. */
  rosaStory: Record<AccountId, RosaStory | null>
}

// ── glossary.json (hand-written copy) ────────────────────────────────────────
export interface GlossaryEntry {
  id: string
  /** The plain term Rosa sees, e.g. "Yearly fee". */
  term: string
  /** The industry's words for it, e.g. ["expense ratio"]. */
  alsoCalled: string[]
  /** One line, 16 words or fewer. */
  short: string
  detail: string
  example: string
  /** Ids of related glossary entries. */
  related: string[]
  /** Outside source. Null for First Leaf's own app terms, which have none. */
  source: { label: string; url: string } | null
}

// ── Loaders ──────────────────────────────────────────────────────────────────
// The data never changes at run time: Practice, session state and every screen
// only read it. Freezing it makes any accidental write throw (and fail the tests).
function deepFreeze<T>(o: T): T {
  if (o && typeof o === 'object' && !Object.isFrozen(o)) {
    Object.freeze(o)
    for (const v of Object.values(o as object)) deepFreeze(v)
  }
  return o
}
for (const d of [accountJson, accountAllClearJson, accountNewJson, activityJson, attentionJson, fundsJson, storyJson, practiceJson, metaJson, glossaryJson]) deepFreeze(d)

export const meta = metaJson as Meta
export const persona = personaJson as Persona
export const funds = fundsJson as Fund[]
export const scenarios = scenariosJson as Scenario[]
export const practiceRules = practiceJson as PracticeRules
export const story = storyJson as Story
export const glossary = glossaryJson as GlossaryEntry[]

const accounts: Record<AccountId, Account> = {
  'rosa-starter': accountJson as Account,
  'rosa-all-clear': accountAllClearJson as Account,
  'rosa-new': accountNewJson as Account,
}
const activity = activityJson as Record<AccountId, ActivityItem[]>
const attention = attentionJson as Record<AccountId, AttentionFlag[]>

export function getFund(ticker: string): Fund | undefined {
  return funds.find((f) => f.ticker === ticker)
}

export function getScenario(id: string): Scenario | undefined {
  return scenarios.find((s) => s.id === id)
}

/** Use through useScenario(); screens never pick an account themselves. */
export function getAccount(id: AccountId): Account {
  return accounts[id]
}

export function getActivity(id: AccountId): ActivityItem[] {
  return activity[id] ?? []
}

export function getAttention(id: AccountId): AttentionFlag[] {
  return attention[id] ?? []
}
