// Typed access to First Leaf's data (Rosa and her accounts are invented; the lineup's names,
// crypto prices, stock anchors and dividends are real, see docs/research/PRICE-ANCHORS.md). Every JSON file in this folder
// has an interface and a loader here. The JSON is generated by
// scripts/generate-data.mjs (only glossary.json is hand-written): never edit it
// by hand.
//
// Screens don't read accounts, activity or attention directly. They go through
// useScenario(), which picks the account for the current demo scenario.
//
// Imports use the @/shared/data/ path so a test-only build can point them at a fixture
// folder (FL_DATA_DIR, see vite.config.ts). The shipped build always uses this folder.

import metaJson from '@/shared/data/meta.json'
import personaJson from '@/shared/data/persona.json'
import fundsJson from '@/shared/data/funds.json'
import accountJson from '@/shared/data/account.json'
import accountAllClearJson from '@/shared/data/account-all-clear.json'
import accountNewJson from '@/shared/data/account-new.json'
import activityJson from '@/shared/data/activity.json'
import attentionJson from '@/shared/data/attention.json'
import scenariosJson from '@/shared/data/scenarios.json'
import practiceJson from '@/shared/data/practice.json'
import storyJson from '@/shared/data/story-p302.json'
import glossaryJson from '@/shared/data/glossary.json'

/** A date as YYYY-MM-DD. */
export type ISODate = string
export type Ticker = 'AAPL' | 'MSFT' | 'NVDA' | 'COST' | 'NKE' | 'AMZN' | 'TSLA' | 'BTC' | 'ETH' | 'SOL'
export type AssetKind = 'stock' | 'crypto'
export type AccountId = 'rosa-starter' | 'rosa-all-clear' | 'rosa-new'
export type ScenarioId = 'normal' | 'all-clear' | 'brand-new'
export type Severity = 'needs-you' | 'heads-up' | 'fyi'

// ── meta.json ────────────────────────────────────────────────────────────────
export interface Meta {
  product: string
  company: string
  asOf: ISODate
  lastClose: ISODate
  lastReview: ISODate
  /** A holding moving this much (0.07 = 7%) in a week gets a heads-up. */
  bigMoveThreshold: number
  wordOfTheDay: string
  currency: string
  fictional: boolean
  dataVersion: number
}

// ── persona.json ─────────────────────────────────────────────────────────────
export interface Persona {
  id: string
  firstName: string
  age: number
  city: string
  job: string
  fictional: boolean
  story: string
  worries: string[]
  devices: { phone: string; laptop: string }
  moments: { P301: string; P302: string; P303: string }
}

// ── funds.json ───────────────────────────────────────────────────────────────
export interface PricePoint {
  date: ISODate
  close: number
}

/** One of the 10 investments (the file keeps its old name, funds.json). */
export interface Fund {
  ticker: Ticker
  name: string
  kind: AssetKind
  /** One or two plain sentences about what it is. */
  about: string
  /** Stocks are modeled between real closes; crypto prices are CoinGecko's. */
  priceSource: 'modeled' | 'coingecko'
  /** 12-month volatility of daily price moves, e.g. 0.25 means 25% a year. */
  volatility: number
  /** "Ups and downs" rating, 1 (calm) to 5 (bumpy), from the volatility. */
  upsAndDowns: number
  /** Real dividends with an ex-dividend date in the last 12 months (stocks only). */
  dividends: { perShare: number; exDate: ISODate; payDate: ISODate }[]
  latestPrice: number
  history: { weekly: PricePoint[]; daily: PricePoint[] }
}

// ── account.json, account-all-clear.json, account-new.json ──────────────────
export interface Holding {
  ticker: Ticker
  kind: AssetKind
  shares: number
  price: number
  value: number
  costBasis: number
  gainLoss: number
  targetShare: number
}

export interface Goal {
  id: string
  name: string
  target: number
  targetDate: ISODate
  measures: 'moneyIn'
  plan: { first: number; monthly: number }
  plannedMoneyInToDate: number
  actualMoneyInToDate: number
  behindBy: number
  plannedMoneyInByTarget: number
  progress: number
}

export interface WeeklyChange {
  from: ISODate
  to: ISODate
  startBalance: number
  deposits: number
  withdrawals: number
  dividends: number
  marketChange: number
  endBalance: number
  totalChange: number
  byFund: { ticker: Ticker; change: number }[]
}

export interface Account {
  id: AccountId
  ownerId: string
  name: string
  fictional: boolean
  openedOn: ISODate
  asOf: ISODate
  lastClose: ISODate
  balance: number
  investedValue: number
  cash: number
  moneyIn: number
  gainLoss: number
  gainLossPercent: number
  dividendsTotal: number
  recurringDeposit: { amount: number; dayOfMonth: number; startedOn: ISODate } | null
  /** Auto-invest buys the mix with each deposit; it never paused (Phase 6). */
  autoInvest: { on: boolean; startedOn: ISODate | null }
  /** Who gets the account if Rosa dies. Null until she names one (Phase 6). */
  beneficiary: { name: string; relationship: string; fictional: true } | null
  targetMix: Partial<Record<Ticker, number>> | null
  holdings: Holding[]
  goal: Goal | null
  weeklyChange: WeeklyChange | null
  history: { date: ISODate; balance: number; moneyIn: number; cash: number }[]
}

// ── activity.json (keyed by account id) ──────────────────────────────────────
interface ActivityBase {
  id: string
  date: ISODate
  settledDate: ISODate
  amount: number
  status: 'completed'
}

export interface DepositActivity extends ActivityBase {
  type: 'deposit'
  kind: 'first' | 'recurring'
}

export interface BuyActivity extends ActivityBase {
  type: 'buy'
  ticker: Ticker
  shares: number
  price: number
  via: 'auto-invest'
}

export interface DividendActivity extends ActivityBase {
  type: 'dividend'
  ticker: Ticker
  perShare: number
  sharesOnExDate: number
  exDate: ISODate
}

export type ActivityItem = DepositActivity | BuyActivity | DividendActivity

// ── attention.json (keyed by account id, most urgent first) ──────────────────
export interface FlagAction {
  kind: 'beneficiary' | 'open-fund'
  label: string
  amount?: number
}

export interface AttentionFlag {
  id: string
  severity: Severity
  date: ISODate
  raisedOn: ISODate
  title: string
  body: string
  nextStep: string
  action: FlagAction | null
  amount: number
  terms: string[]
  route: 'activity' | 'overview' | 'fund' | 'glossary' | 'settings'
  newSinceLastReview: boolean
  activityId?: string
  ticker?: Ticker
  /** Big-move alerts: the week's price move, e.g. 0.08 means up 8%. */
  movePercent?: number
}

// ── scenarios.json ───────────────────────────────────────────────────────────
export interface Scenario {
  id: ScenarioId
  label: string
  description: string
  accountId: AccountId
}

// ── practice.json ────────────────────────────────────────────────────────────
export interface PracticeRules {
  startingCash: number
  fictional: boolean
  minOrder: number
  maxDecimals: number
  fractionalShares: boolean
  tradeFee: number
  priceDate: ISODate
  funds: Ticker[]
  timeMachine: { from: ISODate; to: ISODate; series: 'weekly'; note: string }
}

// ── story-p302.json ──────────────────────────────────────────────────────────
/** One point on a head-start line: her age and what the money could be worth then. */
export interface HeadStartPoint {
  age: number
  value: number
}

export interface StoryClaim {
  id: string
  /** Which chapter of Your money story states it (1–4). */
  chapter: number
  text: string
}

/** Rosa's own facts for one account, recomputed by rules R1–R4. */
export interface RosaStory {
  accountId: AccountId
  pointOfView: string
  facts: {
    openedOn: ISODate
    firstDeposit: number
    moneyIn: number
    balance: number
    earned: number
    depositsShare: number
    lastClose: ISODate
    /** The largest 10-trading-day fall in her portfolio value, April 15 to Aug. 15, 2026. */
    dip: {
      window: { from: ISODate; to: ISODate }
      tradingDays: number
      highDate: ISODate
      highBalance: number
      lowDate: ISODate
      lowBalance: number
      /** Dollars the market took off her balance (deposits and dividends taken out). */
      fall: number
      drop: number
      /** The month of the low, spelled out ("May"). */
      month: string
    }
    atLow: { date: ISODate; balance: number; moneyIn: number; below: number }
    after: {
      backAboveDate: ISODate
      backAboveBalance: number
      backAboveMoneyIn: number
      deposits: { date: ISODate; amount: number }[]
      depositsInvested: boolean
      upNow: number
    }
  }
  claims: StoryClaim[]
}

export interface Story {
  id: string
  title: string
  fictional: boolean
  pointOfView: string
  assumptions: {
    annualRate: number
    compounding: string
    contributionTiming: string
    endAge: number
    note: string
  }
  /** Section 3, "Your head start" (Phase 6.1): two lines, both Rosa, from her age now to 65. Rules T1–T3. */
  headStart: {
    personaId: string
    startAge: number
    endAge: number
    /** Her recurring deposit: what "keep going" adds each month. */
    monthly: number
    delay: { min: number; max: number; step: number; default: number }
    add: { min: number; max: number; step: number; default: number }
    /** For each delay, the smallest whole monthly amount that catches up at 65, or null if none on the slider does. */
    catchUp: { years: number; monthly: number | null }[]
    accounts: Record<AccountId, { start: number; keepGoing: HeadStartPoint[]; laterDefault: HeadStartPoint[] }>
  }
  sources: { label: string; url: string }[]
  /** Per account; null for an account with no history yet. */
  rosaStory: Record<AccountId, RosaStory | null>
}

// ── glossary.json (hand-written copy) ────────────────────────────────────────
export interface GlossaryEntry {
  id: string
  /** The plain term Rosa sees, e.g. "Yearly fee". */
  term: string
  /** The industry's words for it, e.g. ["expense ratio"]. */
  alsoCalled: string[]
  /** One line, 16 words or fewer. */
  short: string
  detail: string
  example: string
  /** Ids of related glossary entries. */
  related: string[]
  /** Where the term is defined: investor.gov, sec.gov, finra.org, sipc.org, irs.gov or consumerfinance.gov (rule L1). */
  source: { label: string; url: string }
}

// ── Loaders ──────────────────────────────────────────────────────────────────
// The data never changes at run time: Practice, session state and every screen
// only read it. Freezing it makes any accidental write throw (and fail the tests).
function deepFreeze<T>(o: T): T {
  if (o && typeof o === 'object' && !Object.isFrozen(o)) {
    Object.freeze(o)
    for (const v of Object.values(o as object)) deepFreeze(v)
  }
  return o
}
for (const d of [accountJson, accountAllClearJson, accountNewJson, activityJson, attentionJson, fundsJson, storyJson, practiceJson, metaJson, glossaryJson]) deepFreeze(d)

export const meta = metaJson as Meta
export const persona = personaJson as Persona
export const funds = fundsJson as Fund[]
export const scenarios = scenariosJson as Scenario[]
export const practiceRules = practiceJson as PracticeRules
export const story = storyJson as Story
export const glossary = glossaryJson as GlossaryEntry[]

const accounts: Record<AccountId, Account> = {
  'rosa-starter': accountJson as Account,
  'rosa-all-clear': accountAllClearJson as Account,
  'rosa-new': accountNewJson as Account,
}
const activity = activityJson as Record<AccountId, ActivityItem[]>
const attention = attentionJson as Record<AccountId, AttentionFlag[]>

export function getFund(ticker: string): Fund | undefined {
  return funds.find((f) => f.ticker === ticker)
}

export function getScenario(id: string): Scenario | undefined {
  return scenarios.find((s) => s.id === id)
}

/** Use through useScenario(); screens never pick an account themselves. */
export function getAccount(id: AccountId): Account {
  return accounts[id]
}

export function getActivity(id: AccountId): ActivityItem[] {
  return activity[id] ?? []
}

export function getAttention(id: AccountId): AttentionFlag[] {
  return attention[id] ?? []
}
